
// This file has been generated by the GUI designer. Do not modify.
namespace PCategoria
{
	public partial class MySQL
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PCategoria.MySQL
			this.Name = "PCategoria.MySQL";
			this.Title = global::Mono.Unix.Catalog.GetString ("MySQL");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
